declare module '~/package.json'
declare module '$'
declare module '@/stores/style.ts'
declare module '@/stores/iconMode.ts'
declare module '@/db.ts'

declare module '@/views/install/main.vue'
declare module '@/views/useIcon/main.vue'
declare module '@/views/Icon/main.vue'
declare module '@/views/FormulaEditor/main.vue'
